name: flutter_loadmore_any
description: A widget that can be pulled up and loaded
version: 0.0.2
homepage: https://github.com/HiFlutter/load_more

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0


